shared:
    image: node:6

jobs:
    A:
        steps:
            - echo: echo test
        requires: [~commit, ~pr]

    # B will run when job C of pipeline 984 succeeds
    B:
        steps:
            - echo: echo test
        requires: [~sd@4:C]
